[project]
name = "airplane_simple_retriever"
version = "0.0.1"
description = "a simple retriver"
author = "parsa"

[ml]
type = "embeddings"
provider = "local"
model_dir = "./models"

[observability]
type = "phoenix"
host_type = "local"

[vectordb]
name = "airplane-simple-retriver"
inRepoPath = "./data"
branchName = "dev"
sourceBranch = "main"
commitHash = "bba2a3edc78115ed85d088064e96ae74a3a4b5b615cc2705ae2404b1d8e036f0"

[project.dependencies]

[ml.embeddings]
port = 1111
model_name = "airplane_simple_retriever_embeddings"
alias = "champion"
tracking = "mlflow"
serving_tech = "liteserve"
