[project]
name = "airplane_simple_retriever"
version = "0.0.1"
description = "a simple retriver"
author = "parsa"

[ml]
type = "embeddings"
provider = "litellm"

[observability]
type = "phoenix"
host_type = "local"

[vectordb]
name = "airplane-simple-retriever"
inRepoPath = "./data"
branchName = "heh"
sourceBranch = "main"
commitHash = "72d9e82d42ac857afca0afb8cc328b1ab537032506b9bd8decc7f315466efe26"

[project.dependencies]

[ml.embeddings]
model = "text-embedding-ada-002"
timeout = 600
caching = false
