[project]
name = "airplane_simple_retriever"
version = "0.0.1"
description = "a simple retriver"
author = "parsa"

[ml]
type = "embeddings"
provider = "litellm"

[observability]
type = "phoenix"
host_type = "local"

[vectordb]
name = "airplane-simple-retriver"
inRepoPath = "./data"
branchName = "dev"
sourceBranch = "main"
commitHash = "13c4e71c61b9aa9ddc7dcd22e9305bfdd2ff3d62b49f8e4b0bf2234c4b831ba0"

[project.dependencies]

[ml.embeddings]
model = "text-embedding-ada-002"
timeout = 600
caching = false
