[project]
name = "airplane_simple_retriever"
version = "0.0.1"
description = "a simple retriver"
author = "parsa"

[ml]
type = "embeddings"
provider = "litellm"

[observability]
type = "phoenix"
host_type = "local"

[vectordb]
name = "airplane-simple-retriver"
inRepoPath = "./data"
branchName = "dev"
sourceBranch = "main"
commitHash = "dee1cb52c4e12ce8fc604f7e58c8db59672e5914ec331662943298ac2d53e6d1"

[project.dependencies]

[ml.embeddings]
model = "text-embedding-ada-002"
timeout = 600
caching = false
